import type { APIRoute } from 'astro';

export const GET: APIRoute = async () => {
  const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.edgeviewfinance.com.au/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/about-us/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/contact/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/privacy-policy/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/finance-ready-assessment/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/services/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/asset-finance/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/business-loans/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/business-overdraft/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/cashflow-finance/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/commercial-property-finance/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/debtor-finance/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/insurance-premium-funding/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/invoice-finance/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/smsf-lending/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.edgeviewfinance.com.au/service/trade-finance/</loc>
    <lastmod>2025-09-10T00:00:00.000Z</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
</urlset>`;

  return new Response(sitemapContent, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
    },
  });
};